---
deploymentservers:
  hosts:
    deployment1:
      ansible_host: 34.76.251.189
      ansible_port: 22
      ansible_ssh_user: jenkins-deploy1
  vars:
    ansible_python_interpreter: /usr/bin/python3
database:
  hosts:
    deployment1:
      ansible_host: 34.76.251.189
      ansible_port: 22
      ansible_ssh_user: jenkins-deploy1
  vars:
    ansible_python_interpreter: /usr/bin/python3
