---
deploymentservers:
  hosts:
    deployment1:
      ansible_host: jenkinsdeploy21986.ddns.net
      ansible_port: 22
      ansible_ssh_user: jenkins
  vars:
    ansible_python_interpreter: /usr/bin/python3
database:
  hosts:
    deployment1:
      ansible_host: jenkinsdeploy21986.ddns.net
      ansible_port: 22
      ansible_ssh_user: jenkins
  vars:
    ansible_python_interpreter: /usr/bin/python3
